server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://128.134.244.183:5432/postgres?currentSchema=class101
    username: postgres
    password: ${datasource.passwd}

  jpa:
    show-sql: false
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update

  rabbitmq:
    host: 10.178.0.12
    username: guest
    password: guest
    port: 5672
  data:
    elasticsearch:
      hosts: 128.134.244.183
      port: 9200
