server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://128.134.244.183:5432/postgres?currentSchema=class101
    username: postgres
    password: ${datasource.passwd}

  jpa:
    show-sql: false
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update

  rabbitmq:
    host: 128.134.244.183
    username: guest
    password: guest
    port: 5672
  data:
    elasticsearch:
      hosts: 10.146.0.4,10.146.0.5,10.146.0.6,10.146.0.7
      port: 9200
